### ISSUE TITLE
Unable to handle LIST chunk

### ISSUE THREAD

**Issue by jaschutte** [kujirahand/wav_io#3]
### Introduction
WAV uses the RIFF format as part of it's header structure. Part of the RIFF format allows for the inclusion of a LIST chunk.

### Problem
As if now, if one were to read a WAV file which contains an LIST chunk (which is quite common for encoders to do), it would not work with this crate.

### Suggestion
I would like to see support for LIST chunks, as in, still be able to read files which contain LIST chunks. I do not expect us to be able to read the LIST chunk itself. Merely being able to read the file like normal would be sufficient, since as of now, it fails to read sample data is a LIST chunk is included.

I am willing to add support for this myself at a later date.

**Comment by kujirahand** [comment]
Thank you for your report. I don't think it's difficult to deal with LIST chunks.

**Comment by jaschutte** [comment]
Although this implementation works for some, it doesn't resolve the most common INFO chunk placement position. I've tackled this problem in my PR.

**Comment by kujirahand** [comment]
@jaschutte Thanks for the complete fix!

**Comment by kujirahand** [comment]
Data could not be read with read_list_chunk function.

**Comment by kujirahand** [comment]
Fxied problem that can not read list chunk's data.
